secrets: secrets.yml
templates:
  globals:
    verify_ssl_certificates: false
    urlrewrite:
      torcache-https:
        regexp: "https:\\/\\/torcache\\.net\\/torrent\\/(?P<id>.*)\\.torrent\\?title=(?P<title>.*)"
        format: "https://torcache.net/torrent/\\g<id>.torrent"
      torcache-http:
        regexp: "http:\\/\\/torcache\\.net\\/torrent\\/(?P<id>.*)\\.torrent\\?title=(?P<title>.*)"
        format: "http://torcache.net/torrent/\\g<id>.torrent"
    headers:
      User-Agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36'
      Referer: 'https://torcache.net/'
      Accept-Encoding: 'deflate, gzip'
    domain_delay:
      torcache.net: 5 seconds
      torrentz.eu: 10 seconds
      beyondhd.me: 10 seconds
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 15

  tv:
    thetvdb_lookup: true
    trakt_lookup: true
    magnets: false
    content_size:
      min: 500
      max: 10000
      strict: no
    pushbullet:
      apikey: '{{ secrets.pushbullet.apikey }}'
      title: '{{tvdb_series_name}} {{tvdb_ep_id}}'
      body: ' {{title}}\nSize {{content_size}}MB\nRating {{tvdb_rating}}\nQuality {{quality}}'
    download:
      path: ./temp/{{series_name}}


  movies:
    magnets: false
    content_size:
      min: 1000
      max: 10000
      strict: no
    imdb_lookup: yes
    trakt_lookup: true
    download:
      path: ./temp/movies
    #    pushbullet:
    #      apikey: '{{ secrets.pushbullet.apikey }}'
    #      title: '{{tmdb_name}} {{imdb_score}}'
    #      body: 'Size: {{content_size}}MB'

  filters:
    regexp:
      reject:
        - '(?i)[ .]cam[ .]'
        - '(?i)[ .]bdscr[ .]'
        - '(?i)[ .]dvdscr[ .]'
        - '(?i)[ .]preair[ .]'
        - '(?i)[ .]ppvrip[ .]'
        - '(?i)[ .]r5[ .]'
        - '(?i)[ .]tc[ .]'
        - '(?i)[ .]ts[ .]'
        - '(?i)[ .]ecc[ .]'
        - '(?i)[ .]avc[ .]'
        - '(?i)[ .]qebs[ .]'
        - "\\b(duo|tri|quadri|tetra|penta)logy\\b":
            from: title
        - "\\b3-?D\\b":
            from: title
        - "\\btrailer\\b":
            from: title
        - "\\bR5\\b":
            from: title
        - "\\bWEBSCR\\b":
            from: title
        - "\\bscreener\\b":
            from: title
        - "\\bTS\\b":
            from: title
        - "\\bCam\\b":
            from: title
        - TrTd TeaM:
            from: title
        - "\\bASAP\\b":
            from: title
        - the.day.of.the.doctor
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'

  movie-queue-request:
    accept_all: true
    seen: local
    retry_failed:
      max_retries: 10
    movie_queue: add
    trakt_list:
      username: '{{ secrets.trakt.username }}'
      password: '{{ secrets.trakt.password }}'
      list: watchlist
      type: movies
    imdb_list:
      list: watchlist
      user_id: '{{ secrets.imdb.user }}'

  movie_search_request:
    template: movies
    movie_queue: accept
    torrent_alive: true
    discover:
      what:
        - emit_movie_queue: true
      from:
        - piratebay:
            category: highres movies
            sort_by: seeds
#        - torrentz: verified
        - rarbg:
            category: [46, 45, 44, 42, 17]
        - kat:
            category: movies

#  torrent:
#    trasmission:
#      path: ./temp/{{series_name}}
#      content_filename: '{{series_name}} - {{series_id}}/{{series_name}} - {{series_id}} - {{quality}}'
#      label: tvshows

#      TASKS
tasks:

# SET SERIES BEGIN
#  get_series_begin:
#    priority: 1
#    trakt_emit:
#      username: '{{ secrets.trakt.username }}'
#      password: '{{ secrets.trakt.password }}'
#      list: watchlist
#    accept_all: yes
#    set_series_begin: yes

# DOWNLOAD SHOWS
#  tvshows:
#    priority: 2
#    template:
#      - filters
#      - torrent
#      - tv
#    torrent_alive: yes
#    set:
#      path: ./temp/{{series_name}}
#      content_filename: '{{series_name}} - {{series_id}}/{{series_name}} - {{series_id}} - {{quality}}'
#      label: tvshows
#    configure_series:
#      from:
#        trakt_list:
#          username: '{{ secrets.trakt.username }}'
#          password: '{{ secrets.trakt.password }}'
#          list: watchlist
#          type: shows
#          strip_dates: yes
#      settings:
#        quality: 1080p h264
#        identified_by: ep
#
#
#    discover:
#      what:
#        - emit_series: yes
#      from:
#        - piratebay:
#            category: "highres tv"
#            sort_by: seeds
#        - rarbg:
#            category: 41
#            use_tvdb: yes
#        - kat:
#            category: tv
#        - torrentz: good

# DOWNLOAD MOVIES
  movie_queue:
    priority: 4
    template: movie-queue-request
    disable: retry_failed

  movie_search_1080p:
    priority: 5
    template: movie_search_request
    quality: '1080p bluray !h265'

  movie_search_720p:
    priority: 6
    template: movie_search_request
    quality: '720p bluray !h265'
    delay: 10 hours

  movie_search_divx:
    priority: 7
    template: movie_search_request
    quality: divx+
    delay: 10 hours

