secrets: secrets.yml
templates:
  globals:
    verify_ssl_certificates: false
    urlrewrite:
      torcache-https:
        regexp: "https:\\/\\/torcache\\.net\\/torrent\\/(?P<id>.*)\\.torrent\\?title=(?P<title>.*)"
        format: "https://torcache.net/torrent/\\g<id>.torrent"
      torcache-http:
        regexp: "http:\\/\\/torcache\\.net\\/torrent\\/(?P<id>.*)\\.torrent\\?title=(?P<title>.*)"
        format: "http://torcache.net/torrent/\\g<id>.torrent"
    headers:
      User-Agent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36'
      Referer: 'https://torcache.net/'
      Accept-Encoding: 'deflate, gzip'
    domain_delay:
      torcache.net: 5 seconds
      torrentz.eu: 10 seconds
      beyondhd.me: 10 seconds
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 15

  inputs:
    magnets: true
    content_size:
      min: 700
      max: 10000
      strict: no
    inputs:
#      - rss: https://www.torrentbytes.net/rss.php?passkey=58f184cea1b3c5aa5e99054bdc64eaa1&username=smulhall&38&5&37&limit=200&SSL=1&direct=1
      - rss:
          url: 'http://www.torlock.com/television/rss.xml'
          silent: true
      - rss:
          url: 'http://showrss.info/feeds/all.rss'
          silent: true
  filters:
    regexp:
      reject:
        - '(?i)[ .]cam[ .]'
        - '(?i)[ .]bdscr[ .]'
        - '(?i)[ .]dvdscr[ .]'
        - '(?i)[ .]preair[ .]'
        - '(?i)[ .]ppvrip[ .]'
        - '(?i)[ .]r5[ .]'
        - '(?i)[ .]tc[ .]'
        - '(?i)[ .]ts[ .]'
        - '(?i)[ .]ecc[ .]'
        - '(?i)[ .]avc[ .]'
        - '(?i)[ .]qebs[ .]'
        - "\\b(duo|tri|quadri|tetra|penta)logy\\b":
            from: title
        - "\\b3-?D\\b":
            from: title
        - "\\btrailer\\b":
            from: title
        - "\\bR5\\b":
            from: title
        - "\\bWEBSCR\\b":
            from: title
        - "\\bscreener\\b":
            from: title
        - "\\bTS\\b":
            from: title
        - "\\bCam\\b":
            from: title
        - TrTd TeaM:
            from: title
        - "\\bASAP\\b":
            from: title
        - the.day.of.the.doctor
    content_filter:
      require:
        - '*.avi'
        - '*.mkv'
        - '*.mp4'
tasks:
  tvshows:
    priority: 1
    template:
      - inputs
      - filters
    torrent_alive: yes
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          password: '{{ secrets.trakt.password }}'
          list: watchlist
          type: shows
          strip_dates: yes
      settings:
        timeframe: 24 hours
        quality: 720p webdl+ h264
        target: 1080p webdl+ h264
        upgrade: true
        identified_by: ep

    set_series_begin: yes

    discover:
      what:
        - trakt_emit:
            username: '{{ secrets.trakt.username }}'
            password: '{{ secrets.trakt.password }}'
            list: watchlist
      from:
        - rarbg:
            category: x264 1080p
        - kat:
            category: tv
        - torrentz: good

    download:
      path: ./temp